version: "3.7"
services:
  redis:
    image: redis:6.2-alpine
    environment:
      REDIS_PASSWORD: $REDIS_PASSWORD
    restart: always
    ports:
      - '6379:6379'
    networks:
      - local-dev-network
    volumes: 
      - redis_data:/var/lib/redis/data
  db:
    image: product-index-db2
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB 
    restart: always
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    networks:
      - local-dev-network
    volumes:
      # To store the database and make sure that it persists even if the container is destroyed and re-created
      - pg_data:/var/lib/postgresql/data

networks:
  # To keep things simple, declare a simple network (no need to get fancy with multiple networks here)
  local-dev-network:

volumes:
  pg_data:
  redis_data: